_wandb:
    value:
        cli_version: 0.22.1
        e:
            35mbhgor2kgol4g270ldzpvcy6vpm344:
                codePath: training_multitask.py
                codePathLocal: training_multitask.py
                cpu_count: 32
                cpu_count_logical: 64
                disk:
                    /:
                        total: "461378736128"
                        used: "165444227072"
                email: mjc030225@gmail.com
                executable: /home/700050058/.conda/envs/fastvideo/bin/python
                git:
                    commit: 2ebd6e8a1643e0a5ee6c48732c31890a7c3e1488
                    remote: https://github.com/mjc030225/Analyzer-training.git
                host: login-1
                memory:
                    total: "134578921472"
                os: Linux-5.14.0-427.13.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /home/700050058/project_feedback_analyzer/training_multitask.py
                python: CPython 3.12.11
                root: /home/700050058/project_feedback_analyzer
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                startedAt: "2025-11-13T13:03:41.780131Z"
                writerId: 35mbhgor2kgol4g270ldzpvcy6vpm344
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.22.1
            "6": 4.57.1
            "12": 0.22.1
            "13": linux-x86_64
epochs:
    value: 50
exp_name:
    value: bert_base_lr2e-5_uf2
lr:
    value: 2e-05
model_name:
    value: bert-base-uncased
unfreeze_layers:
    value: 2
use_rule:
    value: true
